在一个方法开始执行之后，将来这个方法肯定是会退出的。方法的退出分为正常结束和异常终止。如果是通过 return 正常结束，则当前栈帧从线程所拥有的栈中弹出，恢复发起调用的方法的栈。如果方法有返回值，JVM 会把返回值压入到发起调用方法的操作数栈中。

为了处理 Java 方法中的异常情况，栈帧中还必须保存一个对此方法异常引用表的引用。当异常抛出时， JVM 先调用 catch 块中的代码，如果没发现 catch 块，方法立即终止，然后 JVM 用栈帧中的信息恢复发起调用的方法的帧，然后再发起调用方法的上下文重新抛出同样的异常。


作者：_dhengyi
链接：https://juejin.cn/post/6962460534658564126
来源：稀土掘金
著作权归作者所有。商业转载请联系作者获得授权，非商业转载请注明出处。